spring.application.name=api-gateway
server.port=8765

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Security (JWT)
jwt.secret=FINCORP_SECRET_KEY_12345678901234567890

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Spring Cloud Gateway Configuration
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Authentication Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authentication-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# User Service
spring.cloud.gateway.server.webflux.routes[1].id=user-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/user/(?<segment>.*), /users/${segment}

# Account Service
spring.cloud.gateway.server.webflux.routes[2].id=account-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://account-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/account/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/account/(?<segment>.*), /accounts/${segment}

# Swagger Configuration 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Swagger UI base path
springdoc.swagger-ui.path=/swagger-ui.html

# Aggregate downstream services
springdoc.swagger-ui.urls[0].name=Authentication Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

springdoc.swagger-ui.urls[2].name=Account Service
springdoc.swagger-ui.urls[2].url=/account/v3/api-docs